# https://github.com/boschkundendienst/guacamole-docker-compose
version: '3.9'

services:
  guacd:
    image: guacamole/guacd
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:13.6
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./pgdata:/var/lib/postgresql/data:rw

  guacamole:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
#      TOTP_ENABLED: true
    image: guacamole/guacamole
    links:
    - guacd
    ports:
    - 8087:8080/tcp # Guacamole is at 'IP:8087/guacamole' not at '/'.
    restart: always
