global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  # cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080', '10.250.196.17:8080']

  # node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.250.196.17:9100']

  # ping-exporter
  - job_name: 'ping-exporter'
    static_configs:
      - targets: ['ping-exporter:9427']

 # snmp
#  - job_name: 'snmp'
#    scrape_interval: 5m
#    scrape_timeout: 1m
#    static_configs:
#      - targets:
#        - 192.168.178.201  # SNMP device.
#    metrics_path: /snmp
#    params:
#      module: [if_mib]
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.